name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    timeout-minutes: 15

    defaults:
      run:
        working-directory: /

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Get timestamp
        run: |
          echo timestamp="$(date +%s)" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          #images: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.AWS_ECR_REPO }}
          tags: |
            type=sha,prefix={{branch}}-
          # ,suffix=-${{ env.timestamp }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          #labels: ${{ steps.meta.outputs.labels }}