name: Build

on:  
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    timeout-minutes: 15

    defaults:
      run:
        working-directory: /

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            latest=true
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check current version
        id: current
        run: |
          CUR=$(curl -sL "https://api.github.com/repos/Sierra1011/backblaze-b2/releases/latest" | jq -r '.tag_name' )
          echo "::set-output name=version::$CUR"
          echo "Released version: $CUR"

      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
        with:
          build-args: |
            VERSION=${{ steps.current.outputs.version }}"
          push: true
          context: ./
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
