name: Changelog Generator
on:
  pull_request:
    branches:
      - prod

jobs:
  changelog:
    name: Changelog Generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: etcdigital/pull-request-changelog@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
