name: Get latest release version

on:
  workflow_dispatch:
  #schedule:
  #  - cron:  '0 30 * * *'

jobs:
  get-version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch latest released version
        id: latest
        run: |
          VER=$(curl -sL "https://api.github.com/repos/Backblaze/B2_Command_Line_Tool/releases/latest" | jq -r '.tag_name' | cut -c 2-)
          echo "::set-output name=version::$VER"
          echo "Available version: $VER"
      
      - name: Check current version
        id: current
        run: |
          CUR=$(curl -sL "https://api.github.com/repos/Sierra1011/backblaze-b2/releases/latest" | jq -r '.tag_name' )
          echo "::set-output name=version::$CUR"
          echo "Released version: $CUR"
      
      - name: Compare versions
        id: compare
        run: |
          if [ "${{ steps.latest.outputs.version }}" = "${{ steps.current.outputs.version }}" ]; then
            echo "::set-output name=update::false"
            echo "Update not needed"
          else
            echo "::set-output name=update::true"
            echo "Update needed"
          fi       
        
      - name: Tag and release
        if: steps.compare.outputs.update == 'true'
        id: create_release
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: main
          tag : ${{ steps.latest.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}